---
authors:
  - joscary
date: "08 Oct 2025"
---

# Get Bikeshare Station Metadata

## Imports

The required Python libraries are imported below

In [1]:
import pandas as pd
import requests

## About

This notebook retrieves metadata about all bikeshare stations within a single network from public API endpoints. The base URL of the API of the single bikeshare network was obtained from the [previous notebook](./01_get_data.ipynb)

## User Inputs

In [2]:
# | label: base-url
base_url = "https://toronto.publicbikesystem.net/customer/gbfs/v3.0"

The following derived variables are created to define the two station API endpoints from [the above](#base-url)

In [3]:
url_info = f"{base_url}/station_information"
url_status = f"{base_url}/station_status"

## Extract

First we retrieve the station information from the `station_information/` endpoint

In [4]:
r_info = requests.get(url_info).json()
df_info = pd.DataFrame.from_records(r_info["data"]["stations"]).convert_dtypes(
    dtype_backend="pyarrow"
)
df_info

,vehicle_types_capacity,vehicle_docks_capacity,station_id,external_id,name,lat,lon,address,capacity,is_charging_station,rental_methods,is_virtual_station,short_name,rental_uris,post_code,is_valet_station,_valet_station_details,cross_street
0,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7000,f8aa7900-e9c7-11ef-984e-124c66246c7d,"[{'text': 'Fort York Blvd / Capreol Ct', 'lan...",43.639832,-79.395954,Fort York Blvd / Capreol Ct,47,False,"[key, transitcard, creditcard, phone]",False,"[{'text': '647-643-9607', 'language': 'en'}, {...",{},<NA>,<NA>,<NA>,<NA>
1,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7001,f8aaeb6e-e9c7-11ef-984e-124c66246c7d,"[{'text': 'Wellesley Station Green P', 'langua...",43.664964,-79.38355,Yonge / Wellesley,23,True,"[key, transitcard, creditcard, phone]",False,"[{'text': '416-617-9576', 'language': 'en'}, {...",{},M4Y 1G7,<NA>,<NA>,<NA>
2,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7002,f8aaef03-e9c7-11ef-984e-124c66246c7d,"[{'text': 'St. George St / Bloor St W', 'langu...",43.667131,-79.399555,St. George St / Bloor St W,19,False,"[key, transitcard, creditcard, phone]",False,"[{'text': '647-643-9615', 'language': 'en'}, {...",{},<NA>,<NA>,<NA>,<NA>
3,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7003,f8ab20ac-e9c7-11ef-984e-124c66246c7d,"[{'text': 'Madison Ave / Bloor St W', 'languag...",43.667018,-79.402796,Madison Ave / Bloor St W,15,False,"[key, transitcard, creditcard, phone]",False,"[{'text': '647-631-4587', 'language': 'en'}, {...",{},<NA>,<NA>,<NA>,<NA>
4,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7005,f8ab51f8-e9c7-11ef-984e-124c66246c7d,"[{'text': 'King St W / York St', 'language': '...",43.648001,-79.383177,King St W / York St,23,False,"[key, transitcard, phone]",False,"[{'text': '647-643-9693', 'language': 'en'}, {...",{},<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8221,14357ab6-c19f-43b3-b838-310fd2347156,"[{'text': 'Ling Rd / Lawrence Ave E', 'languag...",43.768912,-79.182878,Ling Rd / Lawrence Ave E,11,False,"[key, transitcard, phone]",False,"[{'text': '', 'language': 'en'}, {'text': '', ...",{},M1E 4V9,<NA>,<NA>,Ling Rd / Lawrence Ave E
1026,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8224,63a3dfee-dcab-49a7-a388-ea2eecb5f61c,"[{'text': '439 Wellington St W', 'language': '...",43.643467,-79.39674,439 Wellington St W,19,False,"[key, transitcard, phone]",False,"[{'text': '', 'language': 'en'}, {'text': '', ...",{},M5V 1E7,<NA>,<NA>,<NA>
1027,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8225,57e264ff-4119-4bb5-9948-e3e7780fe08e,[{'text': 'Ellesmere Rd / Highland Creek Trail...,43.780934,-79.212934,Ellesmere Rd / Highland Creek Trail,11,False,"[key, transitcard, phone]",False,"[{'text': '', 'language': 'en'}, {'text': '', ...",{},M1E 4T1,<NA>,<NA>,<NA>
1028,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8226,8eb5187d-d935-40c0-83f4-43f3e930cd12,"[{'text': 'O'Connor Dr / Dohme Ave', 'language...",43.710353,-79.309358,O'Connor Dr / Dohme Ave,15,False,"[key, transitcard, phone]",False,"[{'text': '', 'language': 'en'}, {'text': '', ...",{},M4B 2T3,<NA>,<NA>,O'Connor Dr / Dohme Ave
1029,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8227,def14f46-e7fe-4e38-9867-653f7e2a197c,"[{'text': 'Keele St / Ewart Ave', 'language': ...",43.686644,-79.473413,Keele St / Ewart Ave,11,False,"[key, transitcard, phone]",False,"[{'text': '1765 Keele St', 'language': 'en'}, ...",{},M6M 3W9,<NA>,<NA>,<NA>

Next, we'll get the station status from the `station_status/` endpoint

In [5]:
r = requests.get(url_status).json()
df_status = pd.DataFrame.from_records(r["data"]["stations"]).convert_dtypes(
    dtype_backend="pyarrow"
)
df_status

,station_id,num_vehicles_available,num_vehicles_disabled,num_docks_available,num_docks_disabled,last_reported,is_installed,is_renting,is_returning,vehicle_docks_available,vehicle_types_available
0,7000,28,0,19,0,2026-04-24T14:52:38.681Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1,7001,0,2,20,0,2026-04-24T14:51:35.224Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
2,7002,6,0,13,0,2026-04-24T14:52:16.788Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
3,7003,0,0,15,0,2026-04-24T14:51:38.654Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
4,7005,18,0,5,0,2026-04-24T14:52:45.338Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
...,...,...,...,...,...,...,...,...,...,...,...
1025,8221,3,0,8,0,2026-04-24T14:53:25.969Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1026,8224,10,0,9,0,2026-04-24T14:52:58.077Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1027,8225,1,0,10,0,2026-04-24T14:52:19.179Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1028,8226,5,0,10,0,2026-04-24T14:51:35.611Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1029,8227,1,1,9,0,2026-04-24T14:51:35.585Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."

## Transform

Next, we'll merge these two outputs using the `station_id` column

In [6]:
df = df_info.merge(df_status, on="station_id", how="left")
df

,vehicle_types_capacity,vehicle_docks_capacity,station_id,external_id,name,lat,lon,address,capacity,is_charging_station,...,num_vehicles_available,num_vehicles_disabled,num_docks_available,num_docks_disabled,last_reported,is_installed,is_renting,is_returning,vehicle_docks_available,vehicle_types_available
0,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7000,f8aa7900-e9c7-11ef-984e-124c66246c7d,"[{'text': 'Fort York Blvd / Capreol Ct', 'lan...",43.639832,-79.395954,Fort York Blvd / Capreol Ct,47,False,...,28,0,19,0,2026-04-24T14:52:38.681Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7001,f8aaeb6e-e9c7-11ef-984e-124c66246c7d,"[{'text': 'Wellesley Station Green P', 'langua...",43.664964,-79.38355,Yonge / Wellesley,23,True,...,0,2,20,0,2026-04-24T14:51:35.224Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
2,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7002,f8aaef03-e9c7-11ef-984e-124c66246c7d,"[{'text': 'St. George St / Bloor St W', 'langu...",43.667131,-79.399555,St. George St / Bloor St W,19,False,...,6,0,13,0,2026-04-24T14:52:16.788Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
3,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7003,f8ab20ac-e9c7-11ef-984e-124c66246c7d,"[{'text': 'Madison Ave / Bloor St W', 'languag...",43.667018,-79.402796,Madison Ave / Bloor St W,15,False,...,0,0,15,0,2026-04-24T14:51:38.654Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
4,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",7005,f8ab51f8-e9c7-11ef-984e-124c66246c7d,"[{'text': 'King St W / York St', 'language': '...",43.648001,-79.383177,King St W / York St,23,False,...,18,0,5,0,2026-04-24T14:52:45.338Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8221,14357ab6-c19f-43b3-b838-310fd2347156,"[{'text': 'Ling Rd / Lawrence Ave E', 'languag...",43.768912,-79.182878,Ling Rd / Lawrence Ave E,11,False,...,3,0,8,0,2026-04-24T14:53:25.969Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1026,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8224,63a3dfee-dcab-49a7-a388-ea2eecb5f61c,"[{'text': '439 Wellington St W', 'language': '...",43.643467,-79.39674,439 Wellington St W,19,False,...,10,0,9,0,2026-04-24T14:52:58.077Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1027,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8225,57e264ff-4119-4bb5-9948-e3e7780fe08e,[{'text': 'Ellesmere Rd / Highland Creek Trail...,43.780934,-79.212934,Ellesmere Rd / Highland Creek Trail,11,False,...,1,0,10,0,2026-04-24T14:52:19.179Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1028,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8226,8eb5187d-d935-40c0-83f4-43f3e930cd12,"[{'text': 'O'Connor Dr / Dohme Ave', 'language...",43.710353,-79.309358,O'Connor Dr / Dohme Ave,15,False,...,5,0,10,0,2026-04-24T14:51:35.611Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."
1029,"[{'vehicle_type_ids': [], 'count': 0}]","[{'vehicle_type_ids': ['ASTRO', 'BOOST', 'CHLO...",8227,def14f46-e7fe-4e38-9867-653f7e2a197c,"[{'text': 'Keele St / Ewart Ave', 'language': ...",43.686644,-79.473413,Keele St / Ewart Ave,11,False,...,1,1,9,0,2026-04-24T14:51:35.585Z,True,True,True,"[{'vehicle_type_ids': ['ICONIC', 'BOOST', 'EFI...","[{'vehicle_type_id': 'BOOST', 'count': 0}, {'v..."